name: tests

on:
  push:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    env:
      CI_ENVIRONMENT: testing 

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' 
          extensions: mbstring, intl, sqlite3, pdo_sqlite, dom, curl
          coverage: xdebug

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ~/.cache/composer
          key: composer-${{ runner.os }}-php-8.1-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-php-8.1-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Load test env (.env.testing -> .env)
        run: |
          if [ -f .env.testing ]; then
            cp .env.testing .env
            echo "Usando .env.testing"
          else
            echo "Falta .env.testing en el repo" >&2
            exit 1
          fi
      - name: Run PHPUnit
        run: vendor/bin/phpunit --colors=always

      - name: Upload coverage (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: build/logs/html

      - name: Upload junit & testdox
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-logs
          path: |
            build/logs/logfile.xml
            build/logs/testdox.*
